### ISSUE TITLE
URGENT: Upgrade PostgreSQL to 11.13

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#110]
[Announcement: Amazon Aurora PostgreSQL 10.x end of support is January 31, 2023](https://repost.aws/questions/QU0ligxMlJSJWhzzgKbKgytQ/announcement-amazon-aurora-postgre-sql-10-x-end-of-support-is-january-31-2023)

Unfortunately, this announcement was not broadcast in a timely manner, so this is now an urgent matter.

Acceptance criteria:

- [x] Successful upgrade in dev deployment, verifying no data loss, and ingestion is functional
- [x] Same for UAT
- [x] Same for Prod

**Comment by chuckwondo** [comment]
Upgrade to my dev stack was successful, and all data appears to be intact. I was able to successfully complete a smoke test ingestion.

@jsrikish and @krisstanton, please post a comment once you each manage to do the same with your dev stacks.

I have kicked off the upgrade in UAT and prepped Prod for upgrade.

**Comment by chuckwondo** [comment]
Successfully upgraded DB in UAT and successfully ran smoke test. Kicked off Prod DB upgrade.

**Comment by chuckwondo** [comment]
All good in Prod!

**Comment by krisstanton** [comment]
Verifying.  My dev stack is now upgraded and works with a passed smoke test.
