### ISSUE TITLE
Configure GitHub OIDC for deploying Cumulus to UAT

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#111]
We currently use individual AWS credentials for GitHub workflows. Aside from the security implications of doing so, this also means we must manually update those creds in the GitHub env secrets once every 90 days, which is rather inconvenient, particularly when we forget to do so, and expired creds cause workflow failures.

- [x] Create OIDC Provider
- [x] Create IAM Role
- [x] Configure role's trust relationship
- [x] Configure GitHub Actions workflow to use OIDC
- [x] Construct least-privilege policy

**Comment by zacharyDez** [comment]
hey @chuckwondo , do you have any alternatives? Can you create keys for a security group? I don't know the alternatives. @edkeeble @alukach, any ideas?

**Comment by zacharyDez** [comment]
Ah, sorry @chuckwondo . Will look into it.

**Comment by chuckwondo** [comment]
There's no need for you took look into anything, unless you're curious.

**Comment by chuckwondo** [comment]
In the AWS account csdap-cumulus-uat-7469:

* created IAM identity provider for GitHub OIDC
* created IAM role named github-oidc with a trust policy that has the GitHub OIDC provider as the principal
* added the following condition to the trust relationship of the github-oidc role, to allow only deployments that refer to the `uat` environment of the NASA-IMPACT/csdap-cumulus repository:
   ```
   "StringLike": {
       "token.actions.githubusercontent.com:sub": "repo:NASA-IMPACT/csdap-cumulus:environment:uat"
   }
   ```

**Comment by chuckwondo** [comment]
I updated the github workflow to use OIDC and attached a policy to the role. The policy is not a least-privilege policy, but we can refine it later.

**Comment by chuckwondo** [comment]
Deployment to UAT succeeded!
