### ISSUE TITLE
For dev/sandbox deployments, in PostToCmr step, only validate, don't publish

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#114]
In the PostToCmr step of the ingest/publish workflow, we want to only validate against UAT CMR instead of publishing.

This is not straightforward to achieve because Cumulus does not provide a "validate only" option. Further, writing custom logic to do so is not simple because the Cumulus code includes the configuration and logic required to query the CMR, so one undesirable option would be to copy the code for the PostToCmr lambda function and modify the copy to only validate. This is obviously a very brittle approach since anytime the Cumulus code changes, we would have to copy and modify again.

Alternatively, we might be able to leverage [proxyquire](https://github.com/thlorenz/proxyquire) to alter the behavior of the lambda function. We would simply write our own lambda function, but have it import and call the Cumulus function. In the Cumulus cmr-client library, there is a `getUrl` module that contains `getIngestUrl` and `getValidateUrl` functions. The PostToCmr lambda function ends up creating a call chain that calls `getIngestUrl` to obtain the appropriate URL for publishing a granule. Using `proxyquire` we should be able to cause the call to `getIngestUrl` to actually call `getValidateUrl`. This way, we won't publish the granule, but we'll still produce an error if the payload is invalid.

The use of `proxyquire` is typically limited to tests, and this approach does still depend on specific implementation details of Cumulus, but the surface area is much smaller and much less likely to change, so it is much less coupled than copying and modifying the original code.

**Comment by kaulfusa** [comment]
@chuckwondo is this still relevant?

**Comment by chuckwondo** [comment]
@kaulfusa, not really. I'm closing this as "not planned."
