### ISSUE TITLE
Destroy Cumulus development deployment in account csdap-cumulus-uat-7469 for Kris

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#118]
Only once the Prod, UAT, and sandbox deployments in the new CBA accounts are fully operational, destroy Chuck's development deployment in account [csdap-cumulus-uat-7469](https://cloud.earthdata.nasa.gov/portal/project/171) by following the "Destroying a Deployment" instructions in this repo's `docs/OPERATING.md` file.

**Acceptance criterion:** all AWS resources related to Kris's development deployment in account csdap-cumulus-uat-7469 are destroyed.

**Comment by krisstanton** [comment]
My Deployment `kris-uat7469` in `csdap-cumulus-uat-7469` has been destroyed and cleaned up.
The most recent destroy scripts are functioning.

**Comment by chuckwondo** [comment]
@krisstanton, I'm closing this for you, but please remember to close issues when you've completed them.

**Comment by krisstanton** [comment]
> @krisstanton, I'm closing this for you, but please remember to close issues when you've completed them.

Thanks for closing for me.  Sorry about that, so far on all these tickets, I've just been moving the status the pull down to 'done'. I will make sure to close the tickets at the bottom of the comment UI as well!
