### ISSUE TITLE
Configure ORCA in Cumulus CBA UAT

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#152]
Configure ORCA in Cumulus CBA UAT

- [x] Complete The Configuration Ticket to the Step: Complete the 'workflow' section in the documentation 
https://github.com/NASA-IMPACT/csdap-cumulus/issues/214
https://nasa.github.io/cumulus-orca/docs/developer/deployment-guide/recovery-workflow/
- [x] Modify Github Actions so our UAT deployments point to CBA UAT rather than non-CBA UAT
- [x] Complete Sandbox Deploy Ticket: https://github.com/NASA-IMPACT/csdap-cumulus/issues/248
- [x] Complete The Remaining Items in the Configuration Ticket - https://github.com/NASA-IMPACT/csdap-cumulus/issues/214
A successful UAT deployment is part of the last step in the Configuration Ticket
- [x] Verify ORCA by running a smoke test and then checking to ensure the granules show up in the back up (via ORCA API https://nasa.github.io/cumulus-orca/docs/developer/api/orca-api/)
  - [ ] Complete a granule Recovery process

**Comment by krisstanton** [comment]
Update: WIP: We have granules being saved in the correct backup location.  In order to actually recover any of these granules, we must modify the Cumulus CLI to route the commands.  See new ticket  #277

**Comment by krisstanton** [comment]
Update: WIP: The Cumulus CLI extensions are only going to be done for tracking recovery job status - Also, that task has been decoupled from this ticket.

**Comment by krisstanton** [comment]
Update: WIP: The recovery job test was triggered on midday on Thursday.  We are expecting to observe restored files between 24 to 48 hours after that job was triggered.  The state machine indicates that the recovery workflow job executed without errors.  Now just waiting to see the files show up in the bucket to prove it worked.
