### ISSUE TITLE
Add CloudFront URL for Cumulus distribution in CBA UAT

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#154]
Add CloudFront URL for Cumulus distribution in CBA UAT.

- [x] make NASD request for CloudFront URL for Cumulus distribution (do we want a custom domain? @kaulfusa)
- [ ] once the CloudFront distribution is created, configure `cumulus_distribution_url` in `app/stacks/cumulus/tfvars/uat.tfvars` with the CloudFront domain (create branch in repo and submit PR)
- [ ] deploy (this may require manual deployment if we have not yet switched GitHub Actions workflow to deploy to CBA UAT instead of original UAT account)

**Comment by chuckwondo** [comment]
NASD ticket created: https://bugs.earthdata.nasa.gov/servicedesk/customer/portal/7/NASD-3477 (currently awaiting info)

**Comment by chuckwondo** [comment]
Aaron has provided the requested information for the NASD ticket. Still waiting for the work to be done, so I'm moving this to the next sprint, but I did add a comment to the ticket asking if we need to supply any more information.

**Comment by kaulfusa** [comment]
@kaulfusa will create new NASD ticket for DNS and push to complete the cloudfront creation

**Comment by chuckwondo** [comment]
EOSDIS Support indicated that they cannot get to this until the week of May 29, so I'm pushing this to the sprint that starts that week.

**Comment by chuckwondo** [comment]
https://data.csdap.uat.earthdata.nasa.gov/ has been created.
