### ISSUE TITLE
Update links in Prod CMR metadata for Planet collection to use Prod custom domain

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#165]
Due to a snafu on the EDC (Earthdata Cloud) side of things, our CloudFront URL for our Cumulus Distribution API was blown away.

The bad news is that we must update the metadata files for all of the granules (~3M) we have already ingested into Production, and republish them to the CMR.

The good news is, this has moved us to create a custom domain name for distribution URLs (data.csda.earthdata.nasa.gov), which is not only much friendlier than a random CloudFront URL, but also prevents the need for performing such an update again, if such an event occurs again.

The effort to update our ingested metadata includes the following:

- [x] Copy all thumbnail files from bucket `csdap-cumulus-prod-public` to `csdap-cumulus-prod-protected` (using the same paths), so that the thumbnails are seen during discovery (see below):
   - [x] Create an s3 inventory of the `csdap-cumulus-prod-protected` bucket and have it stored at `s3://csdap-cumulus-prod-internal/s3-inventories` (this will take up to 48 hours to be produced)
   - [x] Create an S3 Batch operation using the s3 inventory to _copy_ (we want to leave the originals in place) all files from `csdap-cumulus-prod-public` to `csdap-cumulus-prod-protected`
- [x] Modify the DiscoverAndQueueGranules workflow to use the value `$.meta.ingestedPathFormat` in place of the `$.meta.providerPathFormat` when the provider host (`$.meta.provider.host`) is the same as the protected/destination bucket (`$.meta.buckets.protected.name`) since that means the source and destination buckets are the same, and we need to use the ingested path instead of the original provider path, because they are not necessarily the same. This can be achieved with a `Choice` type state in the workflow (name it `"SelfDiscovery?"`) inserted after the `"RuleEnabled?"` state, followed by a `Pass` type state (named `"UseIngestedPathFormat"`) that replaces `$.meta.providerPathFormat` with `$.meta.ingestedPathFormat`.

**To test in the sandbox:**

- [x] Deploy changes to IngestAndPublishGranule (as described above) to the sandbox
- [x] Modify the PSScene3Band___1_SmokeTest rule to include a new "meta" property named `"ingestedPathFormat"` (following the `"providerPathFormat"`) with a value of `"'planet/PSScene3Band/'yyyyMMdd_HH"`
- [x] Enable and run the rule PSScene3Band___1_SmokeTest
   ```
   make bash
   cumulus rules enable --name PSScene3Band___1_SmokeTest
   cumulus rules run --name PSScene3Band___1_SmokeTest
   ```
- [x] Confirm that the new `"UseIngestedPathFormat"` state is _not_ executed (i.e., the `"SelfDiscovery?"` choice is false)
- [x] Replace your planet provider in the Cumulus DB:
   ```
   cumulus providers replace --data '{"id":"planet", "protocol":"s3", "host":"'csda-${CUMULUS_PREFIX}-protected-7894'"}'
   ```
- [x] Run the rule PSScene3Band___1_SmokeTest again
- [x] Confirm that  the new `"UseIngestedPathFormat"` state _is_ executed (i.e., the `"SelfDiscovery?"` choice is true)
- [x] Once these tests look good
   - [x] Restore your planet provider:
      ```
     cumulus providers replace --data '{"id":"planet", "protocol":"s3", "host":"'csda-${CUMULUS_PREFIX}-provider-7894'"}'
      ```
   - [x] Add a `"meta.ingestedPathFormat"` property with an appropriate value to all of the other rule files
   - [x] submit a PR

**To test in UAT**, once tested in the sandbox, as described above, and the PR is approved and merged, and github actions deploy the changes to UAT:

- [x] Copy the contents of the `csdap-uat-public` bucket to the `csdap-uat-protected` bucket to get the thumbnails into the protected bucket for discovery
- [x] Wait for GitHub deploy to UAT to succeed
- [x] Checkout and pull the `main` branch, which should contain all of the changes from the merged PR from above
    ```
    git checkout main
    git pull
    ```
- [x] Run `DOTENV=.env.uat make create-data-management-items`
- [x] Enable and run the rule PSScene3Band___1_SmokeTest
   ```
   DOTENV=.env.uat make bash
   cumulus rules enable --name PSScene3Band___1_SmokeTest
   cumulus rules run --name PSScene3Band___1_SmokeTest
   ```
- [x] In the new execution of the DiscoverAndQueueGranules workflow triggered by running the rule above, confirm that the new `"UseIngestedPathFormat"` state is _not_ executed (i.e., the `"SelfDiscovery?"` choice is false)
- [x] Replace your planet provider in the Cumulus DB:
   ```
   DOTENV=.env.uat make bash
   cumulus providers replace --data '{"id":"maxar", "protocol":"s3", "host":"csdap-uat-protected"}'
   ```
- [x] Enable and run the rule `WV03_MSI_L1B___1_UAT`
   ```
   DOTENV=.env.uat make bash
   cumulus rules enable --name WV03_MSI_L1B___1_UAT
   cumulus rules run --name WV03_MSI_L1B___1_UAT
   ```
- [x] Confirm that  the new `"UseIngestedPathFormat"` state _is_ executed (i.e., the `"SelfDiscovery?"` choice is true)
- [x] Confirm that thumbnails are visible: <https://search.uat.earthdata.nasa.gov/search/granules?p=C1242485646-CSDA&pg[0][v]=f&pg[0][gsk]=-start_date&q=wv03&tl=1684194909.111!3!!>
- [x] Hover over one of the thumbnails and confirm that the hostname in the link is `data.csda.uat.earthdata.nasa.gov`
- [x] Once these tests look good, restore the planet provider to its previous value:
   ```
   DOTENV=.env.uat make bash
   cumulus providers replace --data app/stacks/cumulus/resources/providers/maxar.json
   ```

**PRODUCTION**

- [x] Wait for all years of WV03_MSI_L1B to be ingested AND the tests above in UAT look good
- [x] Approve the pending GitHub deployment to Prod
- [x] Run `DOTENV=.env.prod make create-data-management-items`
- [x] Replace the providers in the Cumulus DB:
   ```
   DOTENV=.env.prod make bash
   cumulus providers replace --data '{"id":"planet", "protocol":"s3", "host":"'csdap-${CUMULUS_PREFIX}-protected'"}'
   cumulus providers replace --data '{"id":"maxar", "protocol":"s3", "host":"'csdap-${CUMULUS_PREFIX}-protected'"}'
   ```
- [x] Wait for deployment to Prod to succeed
- [x] Run `DOTENV=.env.prod make bash` to enter the Docker container
- [x] Enable and run the PSScene3Band___1_SmokeTest rule to confirm that the URLs are updated to include the hostname `data.csda.earthdata.nasa.gov` in the CMR (check Earthdata Search to confirm). If all looks good, proceed with the following steps
- [ ] Enable and run each rule for PSScene3Band

     ```
     DOTENV=.env.prod make bash
     cumulus rules enable --name PSScene3Band___1_YYYY
     cumulus rules run --name PSScene3Band___1_YYYY
     ```

  - [x] PSScene3Band___1_2015
  - [x] PSScene3Band___1_2016
  - [x] PSScene3Band___1_2017
  - [x] PSScene3Band___1_2018
  - [x] PSScene3Band___1_2019_H1
  - [x] PSScene3Band___1_2019_Q3
  - [x] PSScene3Band___1_2019_Q4
  - [x] PSScene3Band___1_2020

**Comment by chuckwondo** [comment]
All 538,105 thumbnails in the csdap-cumulus-prod-public bucket were copied to the csdap-cumulu-prod-protected bucket.

**Comment by chuckwondo** [comment]
PSScene3Band___1_2017 got all the way through 11/28/2017 and then the DiscoverAndQueueGranules workflow failed with the following error (execution 29923197-a290-424a-8cd6-69df476ea869):

```plain
The state/task 'arn:aws:lambda:us-west-2:339197775982:function:cumulus-prod-QueueGranules' returned a result with a size exceeding the maximum number of bytes service limit.
```

There were 616099 out of 618269 discovered, with fewer than 200 errors.

I'm skipping retrying 11/29-12/31/2017 for now, in favor of running 2018 overnight tonight. This will also allow us to see if we encounter the same issue for 2018.

We'll circle back to finish up 2017 later, for which I'll create a new issue.

**Comment by chuckwondo** [comment]
Created [issue for next sprint to address Maxar (WorldView) collections](https://github.com/NASA-IMPACT/csdap-cumulus/issues/170), limiting this issue to only the Planet (PSScene3Band) collection.

**Comment by chuckwondo** [comment]
Workflow for PSScene3Band___1_2018 was kicked off on 5/23 at approx. 7:30PM Eastern. Expect completion near 2-3PM Eastern 5/24.

**Comment by chuckwondo** [comment]
Updating 2018 failed near the end of Nov as well. Created new ticket to address later: #171 

To avoid this for 2019, @jsrikish created 2 new rules:

- PSScene3Band___1_2019_H1 covering the first half (hence, H1) of 2019
- PSScene3Band___1_2019_H2 covering the second half (hence, H2) of 2019

She kicked off the first half at about 1:16 PM Central time May 24.

**Comment by chuckwondo** [comment]
@jsrikish and @krisstanton, unfortunately, the process failed yet again, but this time with a different error, although still on the QueueGranules step:

```
The cause could not be determined because Lambda did not return an error type. Returned payload: {"errorMessage":"2023-05-25T11:15:21.397Z c03addb5-25cb-4487-bcab-b1c4f6e3c928 Task timed out after 900.14 seconds"}
```

It failed while attempting to queue granules for 6/3/2019, so I created a new issue to finish this up: #174

Would one of you (or pair up, if you like), create 2 new rules to take the place of `PSScene3Band___1_2019_H2` in order to avoid that rule from also failing. Just copy `PSScene3Band___1_2019_H2` twice:

- PSScene3Band___1_2019_Q3 (change the END date to Oct. 1)
- PSScene3Band___1_2019_Q4 (change the START date to Oct. 1)

Remember to add them to Prod, then enable and run Q3, and once that finishes, enable and run Q4.

**Comment by krisstanton** [comment]
Just some quick updates for end of Sprint

-Deployment to Prod Completed with success.
-We then did Rules enable and then Rules run PSScene3Band__1_2020

Verifying that the run started
-Earthdata Search showing 84,887 granules for all of 2020
Jayanthi verified the AWS Logs, I am looking at Earthdata
I am now seeing the first granules to have the new URL
```
{
      "rel": "http://esipfed.org/ns/fedsearch/1.1/data#",
      "title": "Download 20200101_005958_1043_1B_Analytic.tif",
      "hreflang": "en-US",
      "href": "https://data.csda.earthdata.nasa.gov/csdap-cumulus-prod-protected/planet/PSScene3Band/20200101_005958_1043_1B_Analytic.tif"
    },
```

For Reference:  
https://search.earthdata.nasa.gov/search/granules/granule-details?p=C2112982481-CSDA&pg[0][v]=f&pg[0][qt]=2020-01-01T00%3A00%3A00.000Z%2C2020-01-01T00%3A59%3A59.000Z&pg[0][gsk]=-start_date&g=G2338138853-CSDA&q=PSScene3BANd&tl=1685031474!3!!&lat=0.0703125

**Comment by chuckwondo** [comment]
PSScene3Band___1_2020 failed due to an infrastructure issue, which we'll address separately: https://github.com/NASA-IMPACT/csdap-cumulus/issues/180

Marking this issue complete, as separate issues have been created for cleaning up the fallout.
