### ISSUE TITLE
Finish metadata link updates in Prod for PSScene3Band 2019 H1

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#174]
During metadata link updates for rule PSScene3Band___1_2019_H1, processing got all the way through 6/2/2019 and then the DiscoverAndQueueGranules workflow (execution c5ab727b-8ab4-46a4-9b4c-dafd570fd51b) failed with the following error:

```
The cause could not be determined because Lambda did not return an error type. Returned payload: {"errorMessage":"2023-05-25T11:15:21.397Z c03addb5-25cb-4487-bcab-b1c4f6e3c928 Task timed out after 900.14 seconds"}
```

There were 456820 discovered out of 575827, with just over 450 errors.

To finish the link updates:

- [x] Create a new rule named PSScene3Band___1_2019_H1_finish_link_updates as a copy of PSScene3Band___1_2019_H1, but with the following startDate:
    ```
    "startDate": "2019-06-03T00:00:00Z",
    ```
- [x] Before the Run, replace the `planet` provider with the modified one which sources the files from our protected bucket
    ```
    cumulus providers replace --data '{"id":"planet", "protocol":"s3", "host":"'csdap-${CUMULUS_PREFIX}-protected'"}'
    ```
- [x] Add the rule to Prod using the Cumulus CLI
- [x] Enable the rule
- [x] Run the rule
- [x] Confirm in Earthdata Search that at least 1 granule from 2019-06-03 and 1 from 2019-06-30 had their download links updated to include the friendly hostname `data.csda.earthdata.nasa.gov`
- [x] After the Run, restore the `planet` provider which sources form the delivery bucket
    ```
    cumulus providers replace --data app/stacks/cumulus/resources/providers/planet.json
    ```

**Comment by krisstanton** [comment]
CLI commands for adding, enabling and running the rules
```
DOTENV=.env.prod make bash
cumulus rules add --data app/stacks/cumulus/resources/rules/PSScene3Band/v1/PSScene3Band___1_2019_H1_finish_link_updates.json
cumulus rules enable --name PSScene3Band___1_2019_H1_finish_link_updates
cumulus rules run --name PSScene3Band___1_2019_H1_finish_link_updates
```

**Comment by krisstanton** [comment]
First run failed.  We have a new ticket to work on to address this issue.  
https://github.com/NASA-IMPACT/csdap-cumulus/issues/185
For now, this issue is put on blocker until #185 is resolved.

**Comment by krisstanton** [comment]
Verified - the granules are being updated and so far we have the correct URL showing up.

**Comment by krisstanton** [comment]
PSScene3Band___1_2019_H1_finish_link_updates is now completed.
Planet provider restored to the original state.
