### ISSUE TITLE
Verify accounts and ORCA prerequisites 

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#213]
Verify accounts and ORCA prerequisites

**Comment by krisstanton** [comment]
API reference:
https://nasa.github.io/cumulus-orca/docs/developer/api/orca-api

**Comment by hbparache** [comment]
Kris, Jayanthi, and Abdelhak have a meeting on Tuesday, September 5th. Plan is to complete this ticket during that meeting
