### ISSUE TITLE
Update direct access descriptions CMR as we migrate granule data to CBA

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#251]
Currently, we have a 'direct access description' on all the granules that reads:
"This link provides direct download access via S3 to the granule" 

This is not accurate entirely accurate because not all direct access links are for granules.
for all granules.
There are also other files such as metadata, thumbnails, etc.

For this description update:
We may need to do a CMR update either just before, or as we migrate items from NGAP to CBA -- or even just after we move items into CBA.

More Detailed 'how' TBD.  (Scripted API Calls, or CMR Update Ingest)
Backlogging this ticket until after the Cumulus Upgrade

**Comment by chuckwondo** [comment]
@krisstanton, these descriptions are generated by Cumulus itself, so we have no direct control over them. Modifying these descriptions would require us to write a custom lambda function and insert it into the IngestAndPublishGranule step function. I would be very surprised if any other Cumulus users have bothered doing this, but I could be wrong.

What's the motivation for this?

**Comment by chuckwondo** [comment]
@krisstanton, I believe you were out last week, so I'm tagging you again to resurface this in your inbox.

**Comment by krisstanton** [comment]
> @krisstanton, these descriptions are generated by Cumulus itself, so we have no direct control over them. Modifying these descriptions would require us to write a custom lambda function and insert it into the IngestAndPublishGranule step function. I would be very surprised if any other Cumulus users have bothered doing this, but I could be wrong.
> 
> What's the motivation for this?

I wrote this ticket after a short conversation Aaron and I had.
At the moment, this ticket is meant to be a placeholder to capture that conversation so that we don't overlook it.

We should follow up with Aaron on the level of effort required.

**Comment by chuckwondo** [comment]
Here's an example for an LPDAAC granule: https://cmr.earthdata.nasa.gov/search/concepts/G2777376514-LPCLOUD.umm_json

Notice that their S3 entries have the same descriptions as we do since (as mentioned) they are generated by Cumulus.

Unless there is some major motivation for changing these, I strongly recommend we don't bother.

**Comment by krisstanton** [comment]
I agree @chuckwondo.  Since it is a very low priority with the possibility of being not completed, I am going to move this to Sprint 5 for now.

**Comment by kaulfusa** [comment]
@krisstanton is this being done with the migration?

**Comment by chuckwondo** [comment]
@kaulfusa, this is not being implemented given my previous comments on this issue. If you feel strongly that this should be done, then we need to obtain specific details, but please read through the previous comments.
