### ISSUE TITLE
AGU Poster 2023

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#264]
AGU session:  
IN020 - Data and Information Services for Interdisciplinary Research and Applications in Earth Science
 
Abstract:
The concept of open science promotes wider sharing of data and collaboration among scientists. NASA's Science Data and Information System (ESDIS) manages NASA's collection of Earth science datasets providing easy access to the scientific community.  

MAXAR® satellite imagery data is available to NASA’s through the National Reconnaissance Office (NRO)  Electro-Optical Commercial Layer (EOCL) contract. The NASA Commercial Smallsat Data Acquisition (CSDA) Program provides an interface for the NASA research community for access to these data. Since its inception as a sustain program, the CSDA Program has been migrating the petabyte-scale Maxar imagery data archive from NASA Center for Climate Simulation (NCCS) to the AWS cloud as well as establishing additional direct to cloud acquisition mechanisms. These data are then ingested into the ESDIS Earthdata Cloud environment using NASA’s Cumulus framework. Cumulus is an open source cloud-based data ingest, archive, distribution, and management system. The data are also cataloged in the Earthdata Common Metadata Repository (CMR) for spatiotemporal search and download through enterprise services including Earthdata Search. Although license restrictions limit NASA CSDA Maxar data holdings to NASA funded investigators, this efficient ingestion and processing methodology significantly enhances the accessibility and utility of MAXAR data for the wider NASA scientific community.

The poster describes the scalable cloud-based architecture and data pipelines to stream, catalog, search, and discover petabytes of MAXAR data for research in the Earthdata Cloud.

Link to the abstract:
https://docs.google.com/document/d/1LTou76y2hyOWa06SjsYwXm_ZixWy-Ptk3FKoC1jTt8Y/edit

**Comment by krisstanton** [comment]
Drafting and editing poster location:
Slide 1 of this page:
https://docs.google.com/presentation/d/1du3XpWDQtCiEUzqW7qMUrKkL4CEnLpW2kZZsvKIgQqo/edit#slide=id.g297d682f6b9_0_274
