### ISSUE TITLE
Update Maxar Metadata Conversion and Cumulus Ingest Tracking for WV03 M1BS

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#267]
- [ ] Query the WV03 B table for **WV03_M1BS_L1B** granules for **2014-2022**
- [ ] Update the **https://docs.google.com/spreadsheets/d/1oeBXaKoTnMrky11kNGAiP7YuueomuXZTGjzIvaxtxQ/edit#gid=929462310**
with total no of granules in DB table for each year

**Comment by hbparache** [comment]
[link to correct spreadsheet](https://docs.google.com/spreadsheets/d/1oeBXaKoTnMrky11kNGAiP7YuueomuXZTGjzIvaxt-xQ/edit?usp=sharing)

**Comment by jsrikish** [comment]
We have added granules to DynamoDB since ingesting granules from MCP.  We will fill this in the next spreadsheet during the next batch of ingestion process
