### ISSUE TITLE
Create a smoke test add on specifically for ORCA - For Metrics Milestone

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#271]
Ref: 	https://docs.google.com/spreadsheets/d/1Xznva0Upb9W9bTqdAndV4pDcwjV8jRRYKFVmgq_9i1c/edit#gid=0
Ref: 	18.4.1	The system shall verify that data can be restored from ORCA
Modify the ORCA smoke test to any specific specifications needed by the Data Metrics and Monitoring System.
Related ticket: https://github.com/NASA-IMPACT/csdap-cumulus/issues/152

Most of this is covered within Ticket #152 
The only additional work here would be to set up some kind of automated integrations into our Data Metrics system.
Perhaps a mechanism for triggering an ORCA specific part of the smoke test for removing a test granule and then restoring it via ORCA, and then reporting back that was completed successfully.
- [x] Mechanism to trigger this test by an operator 
- - [ ] Documented well enough for an operator to perform
- [ ] Machine Interface to trigger and receive a response (if that is feasible) This is so that the system that made the API / Automated function call can receive a response and use that information how ever it may need to.

**Comment by krisstanton** [comment]
Related Ticket (prerequisite / parent ticket)
https://github.com/NASA-IMPACT/csdap-cumulus/issues/270

**Comment by hbparache** [comment]
Maybe don't need?

**Comment by krisstanton** [comment]
UPDATE: This is another ticket where recent discussions and plans have made this ticket no longer necessary.
In detail: We are now going to have Manifests auto generated for all PROD (and ORCA) Files which are processed by the Observability Service DAG processes.  This process will reconcile which granules are ingested, backed up and published.
