### ISSUE TITLE
Update PSScene3Band collection definition

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#285]
We need to update the PSScene3Band collection definition in `app/stacks/cumulus/resources/collections/PSScene3Band___1.json` to address the following items:

- Update url_path to provide more granularity for navigation (i.e., so that we do not have _all_ granule files directly under the path `planet/PSScene3Band`)
- Update files list such that thumbnails are ingested into the public bucket

- [x] PREREQUISITE: #305 

Acceptance criteria:

- [x] `url_path` is changed from `planet/PSScene3Band` to `{cmrMetadata.CollectionReference.ShortName}___{cmrMetadata.CollectionReference.Version}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, YYYY)}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, MM)}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, DD)}/{cmrMetadata.GranuleUR}`
- [x] `files` list is updated to contain 2 entries instead of only 1 entry:
  - [x] current entry, but with `_thumb` changed to `-BROWSE.png` (note dash `-`, not underscore `_`)  within regex
  - [x] new entry (copied from existing) matching _only_ `-thumb.png` (note dash `-`, not underscore `_`) and "type" set to "browse" and "bucket" set to "public"

**Comment by krisstanton** [comment]
Since this is a migration ingest, and we will not want to keep the collection around.  I was trying to think of the best place to put the original and migration collection in the code repo.  Instead of the repo, I settled on posting it here in this ticket, in context.

Here is the original PSScene Collection Definition (Not the migration, but the original that we will need to be partly reverted back to after the PSScene migration is complete).

```
{
  "name": "PSScene3Band",
  "version": "1",
  "duplicateHandling": "replace",
  "granuleId": ".*",
  "granuleIdExtraction": "^(\\d{8}_\\d{6}_.+)(?:_\\dB_.+|_thumb.*|_cmr[.]json|_metadata[.]json)$",
  "sampleFileName": "20160628_204526_1_0c74_3B_Analytic_DN_metadata.xml",
  "ignoreFilesConfigForDiscovery": true,
  "url_path": "planet/PSScene3Band",
  "files": [
    {
      "regex": "^(\\d{8}_\\d{6}_.+)(?:_\\dB_.+|_thumb.*|_cmr[.]json|_metadata[.]json)$",
      "sampleFileName": "20160628_204526_1_0c74_3B_Analytic_DN_metadata.xml",
      "bucket": "protected"
    }
  ],
  "meta": {
    "preferredQueueBatchSize": 1,
    "prefixGranuleIds": true,
    "granuleRecoveryWorkflow": "OrcaRecoveryWorkflow"
  }
}
```

**Comment by krisstanton** [comment]
Here is the final version of the collection definition.
```
{
  "name": "PSScene3Band",
  "version": "1",
  "duplicateHandling": "replace",
  "granuleId": ".*",
  "granuleIdExtraction": "^(\\d{8}_\\d{6}_.+)(?:_\\dB_.+|_thumb.*|_cmr[.]json|_metadata[.]json)$",
  "sampleFileName": "20160628_204526_1_0c74_3B_Analytic_DN_metadata.xml",
  "ignoreFilesConfigForDiscovery": true,
  "url_path": "{cmrMetadata.CollectionReference.ShortName}___{cmrMetadata.CollectionReference.Version}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, YYYY)}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, MM)}/{dateFormat(cmrMetadata.TemporalExtent.SingleDateTime, DD)}/{cmrMetadata.GranuleUR}",
  "files": [
    {
      "regex": "^(\\d{8}_\\d{6}_.+)(?:_\\dB_.+|-BROWSE.png|_cmr[.]json|_metadata[.]json)$",
      "sampleFileName": "20160628_204526_1_0c74_3B_Analytic_DN_metadata.xml",
      "type": "data",
      "bucket": "protected"
    },
    {
      "regex": "^(\\d{8}_\\d{6}_.+)(?:.*-thumb.png)$",
      "sampleFileName": "20150601_090322_090c-thumb.png",
      "type": "browse",
      "bucket": "public"
    }
  ],
  "meta": {
    "preferredQueueBatchSize": 1,
    "prefixGranuleIds": true,
    "granuleRecoveryWorkflow": "OrcaRecoveryWorkflow"
  }
}

```
