### ISSUE TITLE
Research, update and confirm Detailed Descriptions to new Ingest Tickets (WV02_Pan_L1B and GE01_Pan_1B)

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#354]
Examine The tickets for ingesting of new datasets WV02_Pan_L1B and GE01_Pan_1B.
Confirm that we have each of the following tickets and that they have all of the correct information and instructions in them.
One thing to remember/consider is that we are back to ingesting new datasets from MCP rather than the recent migration ingests from NGAP.
- [x] Tickets Created during planning
- [x] WV02_Pan_L1B
  - [x] Confirmed: #348
  - [x] Confirmed: #350
  - [x] Confirmed: #349
- [x] GE01_Pan_1B
  - [x] Confirmed: #351
  - [x] Confirmed: #352
  - [x] Confirmed: #353

**Comment by hbparache** [comment]
Draft completed, want to check in with Kris (maybe Chuck) before proceeding

**Comment by hbparache** [comment]
Brad - WV02 Pan doc not updated, Jayanthi looking into it 
Then Jayanthi will review steps with Kris
Then Brad to restore

**Comment by jsrikish** [comment]
GE01 steps are the same as WV02. Edits will be made in the next spring for GE01 when we start to work on it.  Kris and I verified the steps to ingest from MCP to CBA
