### ISSUE TITLE
Upgrade Cumulus to version 11.1.0

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#40]
Upgrade Cumulus to version 11.1.0 by following the steps:

- Perform the [prerequisites](https://github.com/NASA-IMPACT/csdap-cumulus#prerequisites). @botanical, since you won't be able to deploy Cumulus (as you don't have access to the AWS account), you don't need to set a value for `AWS_PROFILE` in your `.env` file that you'll create from the `.env.example` file.
- Run `make docker`
- Follow the [upgrade steps](https://github.com/NASA-IMPACT/csdap-cumulus/blob/main/docs/DEVELOPMENT.md#upgrading-to-the-next-version-in-the-upgrade-path). @botanical, again, since you don't have AWS access, simply follow the first 4 steps. If you can successfully complete the first 4 steps, you can then create a PR, and I'll pull the changes and confirm that I can deploy your changes.

**Comment by chuckwondo** [comment]
@botanical, you should now have access to the CSDAP Cumulus UAT AWS account.

I've also updated this ticket to refer to version 11.1.0, not 11.0.0, since 11.1.0 was just released. Please use the latest.

Finally, I've just merged another branch into main, so please be sure to pull the latest from main again, before creating a new `cumulus-upgrade-11.1.0` branch for this work.

Please ping me if you have any questions or run into any problems.

**Comment by botanical** [comment]
https://github.com/NASA-IMPACT/csdap-cumulus/pull/42 PR to upgrade to 11.1.0 has been merged and deploying to UAT was successful https://github.com/NASA-IMPACT/csdap-cumulus/runs/6010085705?check_suite_focus=true

**Comment by chuckwondo** [comment]
Deployed to Prod
