### ISSUE TITLE
MCP DynamoDB Record Deletion of Ingested files

### ISSUE THREAD

**Issue by jsrikish** [NASA-IMPACT/csdap-cumulus#420]
- [x] Completion of Ticket: https://github.com/NASA-IMPACT/csdap-cumulus/issues/410
- [x] Get the list of granule keys to be deleted for the ingested granules into NGAP (final outputs from ticket #410 ) 
  - For the last part of the mcp delete task, removing the DynamoDB, the lists are found here:
Note, this is these are the same csv file lists that were used for the S3 Batch Operation.
```
Bucket: csdap-maxar-delivery
Dir where CSV files are: utils/kris/MCP_MAXAR_CLEANUP_2024/batch_operations/input_files/
``` 
- [ ] WV04
- [ ] WV03
- [ ] WV02
- [ ] WV01
- [ ] GE01

-  Tested the code in the dev env and created a new branch
https://github.com/NASA-IMPACT/csdap-cumulus/tree/feature-utils-record-manipulation

**Comment by krisstanton** [comment]
Ticket #410 is now completed.

For the last part of the mcp delete task, removing the DynamoDB, the lists are found here:
Note, this is these are the same csv file lists that were used for the S3 Batch Operation.
```
Bucket: csdap-maxar-delivery
Dir where CSV files are: utils/kris/MCP_MAXAR_CLEANUP_2024/batch_operations/input_files/
```

**Comment by jsrikish** [comment]
Using the DAG to accomplish the task -- #134
