### ISSUE TITLE
Configure Cumulus to use Cognito instead of TEA for distribution

### ISSUE THREAD

**Issue by chuckwondo** [NASA-IMPACT/csdap-cumulus#6]
Once Cumulus is upgraded to 9.3.0 (#79), we must configure it to use Cognito instead of TEA (Thin Egress App) for distribution.

Corresponding Trello card: https://trello.com/c/Yl8VCCk3

This issue was originally created in the wrong repo: https://github.com/NASA-IMPACT/csdap-ingest/issues/80

**Comment by chuckwondo** [comment]
References:

- [Cumulus 9.3.0 Release Notes](https://github.com/nasa/Cumulus/releases/tag/v9.3.0)
- [Migrate from TEA deployment to Cumulus Distribution](https://nasa.github.io/cumulus/docs/upgrade-notes/cumulus_distribution_migration)
- [Using the Cumulus Distribution API](https://nasa.github.io/cumulus/docs/deployment/cumulus_distribution)

See https://github.com/nasa/cumulus-template-deploy/blob/master/cumulus-tf/main.tf#L129, which is a comment regarding swapping the new Cumulus Distribution API in place of TEA.

Corresponding changes will need to be made in this repo's `cumulus-tf/main.tf` file.

@rodrigoalmeida94, if you want to attempt to deploy your own Cumulus stack before attempting to make any changes for this issue, please follow the instructions in this repo's `README.md` (starting with the `main` branch) and let me know if you have any trouble.

**Comment by rodrigoalmeida94** [comment]
Thanks a lot @chuckwondo!

 I wasn't able to generate the AWS credentials to perform my own development deployment - It seems the NGAP cloudtamer.io portal](https://cloud.earthdata.nasa.gov) is down? Not sure if I'm missing something or if I could deploy this using my UAH credentials?

In the meanwhile, I started a [branch](https://github.com/NASA-IMPACT/csdap-cumulus/pull/8) with the most straightforward changes from the instructions, in order to get a bit more familiar with the repository.

**Comment by chuckwondo** [comment]
I pulled the branch, added `plan` targets to `Makefile`, and committed the changes.

I ran `make plan` (or `make cumulus-tf/plan`) and encountered the following errors, but I didn't get a chance to address work on fixing them.  Let me know if you get a chance to work on resolving them.  If not, I'll work on them after wrapping up my other PR:

```plain
Error: Reference to undeclared local value

  on cumulus_distribution.tf line 10, in resource "aws_s3_bucket_object" "bucket_map_yaml_distribution":
  10:     protected_buckets = local.protected_bucket_names,

A local value with the name "protected_bucket_names" has not been declared.


Error: Reference to undeclared local value

  on cumulus_distribution.tf line 11, in resource "aws_s3_bucket_object" "bucket_map_yaml_distribution":
  11:     public_buckets = local.public_bucket_names

A local value with the name "public_bucket_names" has not been declared.


Error: Reference to undeclared local value

  on cumulus_distribution.tf line 14, in resource "aws_s3_bucket_object" "bucket_map_yaml_distribution":
  14:     protected_buckets = local.protected_bucket_names,

A local value with the name "protected_bucket_names" has not been declared.


Error: Reference to undeclared local value

  on cumulus_distribution.tf line 15, in resource "aws_s3_bucket_object" "bucket_map_yaml_distribution":
  15:     public_buckets = local.public_bucket_names

A local value with the name "public_bucket_names" has not been declared.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 25, in module "cumulus_distribution":
  25:   api_url                  = var.cumulus_distribution_url

An input variable with the name "cumulus_distribution_url" has not been
declared. This variable can be declared with a variable
"cumulus_distribution_url" {} block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 31, in module "cumulus_distribution":
  31:   lambda_subnet_ids        = var.lambda_subnet_ids

An input variable with the name "lambda_subnet_ids" has not been declared.
This variable can be declared with a variable "lambda_subnet_ids" {} block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 32, in module "cumulus_distribution":
  32:   oauth_client_id          = var.csdap_client_id

An input variable with the name "csdap_client_id" has not been declared. This
variable can be declared with a variable "csdap_client_id" {} block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 33, in module "cumulus_distribution":
  33:   oauth_client_password    = var.csdap_client_password

An input variable with the name "csdap_client_password" has not been declared.
This variable can be declared with a variable "csdap_client_password" {}
block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 34, in module "cumulus_distribution":
  34:   oauth_host_url           = var.csdap_host_url

An input variable with the name "csdap_host_url" has not been declared. This
variable can be declared with a variable "csdap_host_url" {} block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 36, in module "cumulus_distribution":
  36:   permissions_boundary_arn = var.permissions_boundary_arn

An input variable with the name "permissions_boundary_arn" has not been
declared. This variable can be declared with a variable
"permissions_boundary_arn" {} block.


Error: Reference to undeclared input variable

  on cumulus_distribution.tf line 40, in module "cumulus_distribution":
  40:   vpc_id                   = var.vpc_id

An input variable with the name "vpc_id" has not been declared. This variable
can be declared with a variable "vpc_id" {} block.


Error: Reference to undeclared input variable

  on main.tf line 137, in module "cumulus":
 137:   tea_external_api_endpoint = var.cumulus_distribution_url

An input variable with the name "cumulus_distribution_url" has not been
declared. This variable can be declared with a variable
"cumulus_distribution_url" {} block.

```

**Comment by rodrigoalmeida94** [comment]
Thank you! I noticed I did not add the new variables to the `cumulus-tf/variables.tf` file so I think that is the reason why some of these errors occurred.

One thing I noticed is that this module asks for a `permissions_boundary_arn` not a `permissions_boundary_name` (I can imagine this can be problematic, since we probably need to pass different ARNs for different environments).

I am also quite unsure where I would fetch the `vpc_id` and the `lambda_subnet_ids` - by looking at the TEA configuration I replaced them with `data.aws_vpc.ngap_vpc.id` and `local.ngap_subnet_ids` respectively.

**Comment by rodrigoalmeida94** [comment]
Re: **AWS secrets naming convention**

I found this [AWS documentation](https://docs.aws.amazon.com/secretsmanager/latest/help-panel/secret-name-and-description-control.html):
> The name can include a path with / characters to enable you to logically group your secrets. This makes performing some operations easier, such as setting permissions, by enabling you to reference all of the secrets in a path with strings like “/pathname/*”.

In [this](https://github.com/external-secrets/kubernetes-external-secrets/issues/178) someone suggests a convention to be enforced similar to what you described (`<env>-<namespace>-<secretname>`) but this is for an add-on for kubernetes.

I'll have a further look next week and prepare a proposal.

**Comment by rodrigoalmeida94** [comment]
I could not find anything specifically from AWS regarding secrets naming convention, except what I posted before from the docs. Therefore this is my proposal:
```
<app>/<env>[-<namespace>]/<secretname>
```
Where:
- `app` is the application name (e.g. `cumulus`)
- `env` is the environment where the secret is applicable to (e.g. `uat`)
- `namespace` is used specifically for `dev` deployments, for instance when we want to setup a personal stack, and should identify the deployment, by using a unique name (e.g. `rodrigo`, making the whole environment part `dev-rodrigo`)
- `secretname` the actual secret name (e.g. `csdap-client-id`).
For sake of consistency I also propose we make use of `-` to separate words in names.

These would then be examples of secret names:
```
cumulus/uat/csdap-client-id
cumulus/dev-rodrigo/csdap-client-id
cumulus/ops/csdap-client-id
```
