### ISSUE TITLE
Standup Cumulus in CBA UAT account

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#86]
Standup Cumulus 13.4.0 in CBA account `csda-cumulus-uat-1686`.

**Comment by edkeeble** [comment]
Out of curiosity, does Cumulus have a documented QA process we can follow for deployments (or, even better, a set of e2e tests we can run against it)? Or is it too dependent on the customization of any given environment to support that?

**Comment by chuckwondo** [comment]
Cumulus deployments are snowflakes, so it is really up to each project to define such a process.

We certainly need to expand on what I have, but I have documented basic e2e smoke testing, which I will go over with Kris and Jayanthi.

**Comment by kaulfusa** [comment]
I have submitted cloudfront endpoints by the NGAP team to be created for the Cumulus API and distribution API but I don't expect them to be available before end of sprint 2 and maybe sprint 3. 

cross account communications for cloud metrics and Cognito service may also be an issue requiring NGAP support

**Comment by chuckwondo** [comment]
@kaulfusa, NGAP won't be able to address those CloudFront tickets until we create the Cumulus resources. Once we do, we'll need to update those tickets with the information that the NGAP folks need.

**Comment by chuckwondo** [comment]
Cumulus is deployed in CBA UAT account, and all providers, collections, and rules have been added to the DB. It is not yet fully operational, as we need to configure it for metrics and distribution (Cognito), but these items will be covered by separate tickets.
