### ISSUE TITLE
Do initial sandbox deploy of Cumulus

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#87]
-Get familiar with getting into the NGAP and the CBA environment
-Meet with Chuck to get initial input on deploying Cumulus (starting points)
-Attempt a cloud sandbox deploy - follow trouble shooting guide and document anything new that comes up

Parent Task: https://github.com/NASA-IMPACT/csdap-cumulus/issues/86

**Comment by chuckwondo** [comment]
Duplicate of #92
