### ISSUE TITLE
Deploy latest/fixed version of Cumulus to NGAP CBA (recurring)

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#88]
-Deploy the latest/fixed version of Cumulus to the CBA (NGAP cloud)
--Confirm that all errors and issues from the last attempt have been addressed / fixed

Parent Task: https://github.com/NASA-IMPACT/csdap-cumulus/issues/86

**Comment by chuckwondo** [comment]
@krisstanton, let's remove this. When we deem it necessary to upgrade Cumulus to a specific version, we should create a specific ticket for that specific version upgrade. Each time we want to perform an upgrade, we'll create a new ticket for a specific upgrade. All of these "catch-all" tickets are just creating clutter.
