### ISSUE TITLE
Handle Cumulus Errors on NGAP CBA (recurring)

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#90]
-Address and fix any deployment related issues.
-For Dependency related issues, coordinate with ESDA (I think?) to have them fix.

Note: Make more specific task tickets as they present themselves.

Parent Task: https://github.com/NASA-IMPACT/csdap-cumulus/issues/86

**Comment by chuckwondo** [comment]
@krisstanton, this is the type of issue that I think you should _not_ create. I recommend deleting this issue. When we run into _specific_ problems, we'll create issues for them. These type of "catch-all" issues just create clutter, as they are never closed by their very nature.
