### ISSUE TITLE
Repeat the Tasks as necessary until Cumulus is running properly on its own in the new NGAP CBA environment.

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csdap-cumulus#91]
Repeat Task #88, #89, #90 as necessary until Cumulus is running properly on its own in the new NGAP CBA environment.

Parent Task: https://github.com/NASA-IMPACT/csdap-cumulus/issues/86

**Comment by chuckwondo** [comment]
@krisstanton, another "catch-all" that I recommend you delete. We should create _specific_ issues as they come up.
